# -*- coding: utf-8 -*-
"""lab_6_4(c).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zcLG3wRyOarJGl1xBFO8dDT6CAXkW5-6
"""

import matplotlib.pyplot as plt

# Configurations
configurations = [
    "Parallel (Load Balancing, auto)",
    "Parallel (Load Balancing, n=1)",
    "Parallel (Load Balancing, threads=1)",
    "Parallel (Load Balancing, n=1, threads=1)",
    "Parallel (Standard Distribution, auto)",
    "Parallel (Standard Distribution, n=1)",
    "Parallel (Standard Distribution, auto, low threads)"
]

# Speedup values
speedups = [0.1168, 0.4936, 0.4027, 0.1196, 0.1042, 0.0988, 0.2186]

# Plot
plt.figure(figsize=(12, 6))
plt.bar(configurations, speedups, color='skyblue')

# Labels and title
plt.xlabel("Configuration")
plt.ylabel("Speedup (Sequential Time / Parallel Time)")
plt.title("Speedup for Different Configurations")
plt.xticks(rotation=30, ha='right')
plt.grid(axis='y', linestyle='--', alpha=0.7)

# Show plot
plt.show()